Repository securesign/fulcio, pull requests merged in 2023-10, with the labels that each got.

#31 chore: do not force push to the release branch
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#35 chore: modify update script to avoid merge conflicts
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#37 chore: remove patches, relying solely on overlays
  redhat/overlays/Dockerfile
  redhat/patches/0001-dockerfile.patch
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#38 chore: use fully qualified image specs
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#41 enable hermetic builds, add label for commit
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#40 Unit tests for rhtap
  .tekton/fulcio-pull-request.yaml
  .tekton/fulcio-push.yaml
  .tekton/fulcio-unit-test.yaml
Labels: approved, lgtm

#44 Remove cron job
  .github/workflows/cronjobs.yaml
Labels: lgtm

#46 :robot: triggering CI on branch 'redhat-v1.4.0' after synching from upstream/v1.4.0
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#47 deps(ubi-minimal): bump to latest sha256
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#49 :robot: triggering CI on branch 'redhat-v1.4.0' after synching from upstream/v1.4.0
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved

#51 feat: Add GH action
  .github/workflows/cronjobs.yaml
Labels: approved, lgtm

#57 chore: remove unit tests from RHTAP pipeline
  .tekton/fulcio-pull-request.yaml
  .tekton/fulcio-push.yaml
Labels: approved, lgtm
